// =============================================
// داده‌های نمونه فازهای پیشرفته
// =============================================

// فاز 1: سیستم پیش‌بینی ترافیک
export const trafficPredictions = {
  currentCongestion: 67,
  predictedCongestion: 72,
  peakHours: ['۰۷:۰۰-۰۹:۰۰', '۱۷:۰۰-۱۹:۰۰'],
  predictedAccidents: 8,
  recommendedRoutes: [
    { from: 'میدان آزادی', to: 'تجریش', alternative: 'بزرگراه همت', timeSaved: '۱۵ دقیقه' },
    { from: 'ونک', to: 'سعادت‌آباد', alternative: 'بزرگراه یادگار', timeSaved: '۲۰ دقیقه' },
    { from: 'تهرانپارس', to: 'ازگل', alternative: 'بزرگراه بابایی', timeSaved: '۲۵ دقیقه' },
  ],
  hourlyPrediction: Array.from({ length: 24 }, (_, i) => ({
    hour: `${i}:00`,
    actual: i < 12 ? 400 + Math.random() * 600 : 300 + Math.random() * 500,
    predicted: i < 12 ? 420 + Math.random() * 580 : 320 + Math.random() * 480,
    confidence: 85 + Math.random() * 10,
  })),
};

// فاز 1: سنسورهای IoT
export const iotSensors = {
  airQuality: [
    { id: 1, location: 'میدان ولیعصر', aqi: 85, status: 'متوسط', pm25: 35, pm10: 52, no2: 28 },
    { id: 2, location: 'پارک ملت', aqi: 62, status: 'خوب', pm25: 22, pm10: 38, no2: 18 },
    { id: 3, location: 'بازار تهران', aqi: 112, status: 'ناسالم', pm25: 48, pm10: 72, no2: 42 },
    { id: 4, location: 'تجریش', aqi: 58, status: 'خوب', pm25: 20, pm10: 35, no2: 15 },
    { id: 5, location: 'راه‌آهن', aqi: 98, status: 'متوسط', pm25: 42, pm10: 65, no2: 38 },
    { id: 6, location: 'سعادت‌آباد', aqi: 71, status: 'متوسط', pm25: 28, pm10: 45, no2: 22 },
  ],
  wasteSensors: [
    { id: 1, location: 'منطقه ۱ - بلوار اندرزگو', fillLevel: 78, temperature: 22, lastCollected: '۲ ساعت پیش' },
    { id: 2, location: 'منطقه ۲ - میدان ونک', fillLevel: 45, temperature: 24, lastCollected: '۴ ساعت پیش' },
    { id: 3, location: 'منطقه ۳ - خیابان شریعتی', fillLevel: 92, temperature: 21, lastCollected: '۱ ساعت پیش' },
    { id: 4, location: 'منطقه ۴ - میدان هروی', fillLevel: 33, temperature: 23, lastCollected: '۵ ساعت پیش' },
    { id: 5, location: 'منطقه ۵ - بلوار فردوس', fillLevel: 67, temperature: 25, lastCollected: '۳ ساعت پیش' },
  ],
  waterSensors: [
    { id: 1, location: 'ایستگاه پمپاژ منطقه ۱', pressure: 4.2, flow: 1250, quality: 98, status: 'سالم' },
    { id: 2, location: 'ایستگاه پمپاژ منطقه ۲', pressure: 3.8, flow: 1180, quality: 96, status: 'سالم' },
    { id: 3, location: 'ایستگاه پمپاژ منطقه ۳', pressure: 3.5, flow: 1120, quality: 94, status: 'هشدار' },
    { id: 4, location: 'ایستگاه پمپاژ منطقه ۴', pressure: 4.0, flow: 1200, quality: 97, status: 'سالم' },
    { id: 5, location: 'ایستگاه پمپاژ منطقه ۵', pressure: 3.2, flow: 1050, quality: 92, status: 'بحرانی' },
  ],
  smartLights: [
    { id: 1, location: 'خیابان ولیعصر - تقاطع ونک', brightness: 85, status: 'فعال', energySaved: '۳۲٪' },
    { id: 2, location: 'بلوار کشاورز', brightness: 70, status: 'فعال', energySaved: '۲۸٪' },
    { id: 3, location: 'میدان تجریش', brightness: 90, status: 'فعال', energySaved: '۳۵٪' },
    { id: 4, location: 'بزرگراه همت', brightness: 95, status: 'فعال', energySaved: '۴۰٪' },
  ],
};

// فاز 2: دستیار هوشمند
export const aiAssistant = {
  suggestions: [
    { id: 1, type: 'ترافیک', message: 'پیشنهاد می‌شود چراغ‌های تقاطع ولیعصر-ونک ۱۵ ثانیه افزایش یابد', priority: 'بالا', confidence: 92 },
    { id: 2, type: 'بودجه', message: 'پیش‌بینی کسری بودجه ۱۲٪ در بخش حمل‌ونقل تا پایان فصل', priority: 'متوسط', confidence: 87 },
    { id: 3, type: 'شکایات', message: 'افزایش ۲۵٪ شکایات در منطقه ۳ - نیاز به بررسی فوری', priority: 'بالا', confidence: 95 },
    { id: 4, type: 'زباله', message: 'بهینه‌سازی مسیر جمع‌آوری می‌تواند ۱۸٪ هزینه‌ها را کاهش دهد', priority: 'متوسط', confidence: 89 },
    { id: 5, type: 'آب', message: 'نشتی احتمالی در شبکه منطقه ۵ - پیشنهاد بازرسی', priority: 'بالا', confidence: 78 },
  ],
  chatHistory: [
    { role: 'user', message: 'وضعیت ترافیک امروز چگونه است؟', time: '۱۰:۳۰' },
    { role: 'ai', message: 'ترافیک در حال حاضر ۶۷٪ ظرفیت است. پیش‌بینی می‌شود تا ساعت ۱۸ به ۷۲٪ برسد. پیشنهاد می‌کنم چراغ‌های هوشمند را در حالت بهینه‌سازی فعال کنید.', time: '۱۰:۳۱' },
    { role: 'user', message: 'کدام مناطق بحرانی هستند؟', time: '۱۰:۳۲' },
    { role: 'ai', message: 'مناطق بحرانی: ۱) میدان ولیعصر (تراکم ۸۵٪) ۲) بازار تهران (تراکم ۹۲٪) ۳) راه‌آهن (تراکم ۷۸٪). پیشنهاد تغییر مسیر برای خودروها.', time: '۱۰:۳۳' },
  ],
};

// فاز 2: گزارش‌های هوشمند
export const smartReports = {
  autoGenerated: [
    { id: 1, title: 'گزارش عملکرد هفتگی - هفته ۴۵', date: '1402/11/12', type: 'عملکرد', aiScore: 94, insights: 12 },
    { id: 2, title: 'تحلیل شکایات ماهانه - آبان', date: '1402/11/01', type: 'شکایات', aiScore: 88, insights: 8 },
    { id: 3, title: 'پیش‌بینی بودجه سه‌ماهه', date: '1402/10/28', type: 'بودجه', aiScore: 91, insights: 15 },
    { id: 4, title: 'تحلیل ترافیک فصلی', date: '1402/10/15', type: 'ترافیک', aiScore: 96, insights: 20 },
  ],
  insights: [
    { category: 'ترافیک', finding: 'تراکم ترافیک در ساعات اوج ۲۳٪ افزایش یافته', impact: 'بالا', recommendation: 'افزایش ظرفیت حمل‌ونقل عمومی' },
    { category: 'شکایات', finding: 'شکایات مربوط به آسفالت ۴۵٪ بیشتر از ماه قبل', impact: 'متوسط', recommendation: 'تخصیص بودجه اضافی برای ترمیم' },
    { category: 'بودجه', finding: 'هزینه‌های انرژی ۱۸٪ کاهش یافته', impact: 'مثبت', recommendation: 'ادامه سیاست‌های بهینه‌سازی' },
    { category: 'پرسنل', finding: 'بهره‌وری کارکنان ۱۲٪ افزایش یافته', impact: 'مثبت', recommendation: 'تقدیر از تیم‌های برتر' },
  ],
};

// فاز 3: دیجیتال توین
export const digitalTwin = {
  cityModel: {
    totalBuildings: 245000,
    totalRoads: 12500,
    totalParks: 350,
    totalBridges: 85,
    population: 8500000,
  },
  simulations: [
    { id: 1, name: 'شبیه‌سازی ترافیک - سناریوی بارندگی', status: 'در حال اجرا', progress: 65, duration: '۲ ساعت' },
    { id: 2, name: 'تأثیر ساخت پل جدید بر ترافیک', status: 'تکمیل', progress: 100, duration: '۴۵ دقیقه' },
    { id: 3, name: 'تحلیل اثرات آلودگی هوا', status: 'در انتظار', progress: 0, duration: '۳ ساعت' },
    { id: 4, name: 'شبیه‌سازی سیلاب - منطقه ۳', status: 'تکمیل', progress: 100, duration: '۱ ساعت' },
  ],
  scenarios: [
    { name: 'افزایش ۲۰٪ جمعیت', impact: { traffic: '+۳۵٪', pollution: '+۲۸٪', services: '-۱۵٪' } },
    { name: 'ساخت مترو خط ۱۰', impact: { traffic: '-۲۵٪', pollution: '-۱۸٪', services: '+۱۰٪' } },
    { name: 'افزایش فضای سبز ۳۰٪', impact: { traffic: '۰٪', pollution: '-۲۲٪', services: '+۵٪' } },
  ],
};

// فاز 3: واقعیت افزوده
export const arFeatures = {
  projects: [
    { id: 1, name: 'پل جدید منطقه ۲', location: { lat: 35.715, lng: 51.404 }, arAvailable: true, completion: 75 },
    { id: 2, name: 'پارکینگ طبقاتی ونک', location: { lat: 35.758, lng: 51.410 }, arAvailable: true, completion: 45 },
    { id: 3, name: 'مرکز فرهنگی تجریش', location: { lat: 35.805, lng: 51.432 }, arAvailable: false, completion: 30 },
  ],
  arExperiences: [
    { id: 1, title: 'بازدید مجازی از پل جدید', type: 'پروژه', duration: '۱۰ دقیقه', rating: 4.8 },
    { id: 2, title: 'تور مجازی پارک ملت', type: 'فضای سبز', duration: '۱۵ دقیقه', rating: 4.9 },
    { id: 3, title: 'بازدید از ایستگاه مترو', type: 'حمل‌ونقل', duration: '۸ دقیقه', rating: 4.7 },
  ],
};

// فاز 3: یکپارچگی سیستم‌ها
export const systemIntegrations = {
  connected: [
    { name: 'سامانه ثبت احوال', status: 'متصل', lastSync: '۵ دقیقه پیش', records: 8500000 },
    { name: 'سامانه مالیاتی', status: 'متصل', lastSync: '۱۰ دقیقه پیش', records: 1250000 },
    { name: 'سامانه پلیس', status: 'متصل', lastSync: '۲ دقیقه پیش', records: 350000 },
    { name: 'سامانه هواشناسی', status: 'متصل', lastSync: '۱ دقیقه پیش', records: 24 },
    { name: 'سامانه اورژانس', status: 'متصل', lastSync: '۳ دقیقه پیش', records: 15000 },
  ],
  pending: [
    { name: 'سامانه آموزش و پرورش', status: 'در انتظار تایید', progress: 75 },
    { name: 'سامانه بانک مرکزی', status: 'در حال توسعه', progress: 45 },
  ],
};

// فاز 4: بلاکچین
export const blockchainData = {
  transactions: [
    { id: '0x1a2b3c4d', type: 'پرداخت عوارض', amount: 2500000, from: 'شهروند ۱۲۳۴', to: 'شهرداری', timestamp: '1402/11/15 10:30', status: 'تایید' },
    { id: '0x2b3c4d5e', type: 'قرارداد پیمانکاری', amount: 5000000000, from: 'شهرداری', to: 'شرکت عمرانی نوین', timestamp: '1402/11/14 14:20', status: 'تایید' },
    { id: '0x3c4d5e6f', type: 'جریمه تخلف', amount: 500000, from: 'شهروند ۵۶۷۸', to: 'شهرداری', timestamp: '1402/11/14 09:15', status: 'تایید' },
    { id: '0x4d5e6f7g', type: 'پرداخت حقوق', amount: 15000000, from: 'شهرداری', to: 'کارمند ۹۰۱۲', timestamp: '1402/11/13 16:45', status: 'تایید' },
    { id: '0x5e6f7g8h', type: 'خرید تجهیزات', amount: 850000000, from: 'شهرداری', to: 'فروشگاه تجهیزات', timestamp: '1402/11/12 11:30', status: 'تایید' },
  ],
  smartContracts: [
    { id: 1, name: 'قرارداد ساخت پل منطقه ۲', value: 5000000000, status: 'فعال', parties: 3, completion: 75 },
    { id: 2, name: 'قرارداد نگهداری فضای سبز', value: 1200000000, status: 'فعال', parties: 2, completion: 100 },
    { id: 3, name: 'قرارداد جمع‌آوری زباله', value: 800000000, status: 'منقضی', parties: 2, completion: 100 },
  ],
  voting: [
    { id: 1, title: 'تصویب بودجه سال ۱۴۰۳', yes: 125000, no: 45000, total: 170000, status: 'فعال', endDate: '1402/12/29' },
    { id: 2, title: 'ساخت پارک جدید در منطقه ۵', yes: 85000, no: 12000, total: 97000, status: 'تکمیل', endDate: '1402/11/10' },
  ],
};

// فاز 4: مدیریت بحران
export const crisisManagement = {
  currentAlerts: [
    { id: 1, type: 'زلزله', severity: 'هشدار', location: 'شمال تهران', magnitude: 3.2, time: '۱۰ دقیقه پیش', status: 'در حال بررسی' },
    { id: 2, type: 'سیلاب', severity: 'خطر', location: 'منطقه ۳', rainfall: 45, time: '۳۰ دقیقه پیش', status: 'فعال' },
    { id: 3, type: 'آتش‌سوزی', severity: 'بحرانی', location: 'بازار تهران', area: '۲۰۰ متر مربع', time: '۱ ساعت پیش', status: 'در حال اطفاء' },
  ],
  resources: [
    { type: 'آتشنشانی', available: 45, deployed: 12, total: 57 },
    { type: 'اورژانس', available: 38, deployed: 8, total: 46 },
    { type: 'پلیس', available: 120, deployed: 25, total: 145 },
    { type: 'آمبولانس', available: 28, deployed: 6, total: 34 },
    { type: 'نجات', available: 15, deployed: 4, total: 19 },
  ],
  evacuationRoutes: [
    { id: 1, name: 'مسیر شمال - پارک ملت', capacity: 50000, current: 12000, status: 'باز' },
    { id: 2, name: 'مسیر شرق - پارک جنگلی لویزان', capacity: 75000, current: 8000, status: 'باز' },
    { id: 3, name: 'مسیر غرب - پارک چیتگر', capacity: 60000, current: 15000, status: 'باز' },
  ],
  simulations: [
    { id: 1, name: 'زلزله ۶ ریشتری', date: '1402/11/10', casualties: 150, damage: '۲۵۰۰ میلیارد', status: 'تکمیل' },
    { id: 2, name: 'سیلاب شدید', date: '1402/11/05', casualties: 45, damage: '۸۰۰ میلیارد', status: 'تکمیل' },
    { id: 3, name: 'حمله سایبری', date: '1402/10/28', casualties: 0, damage: '۱۵۰ میلیارد', status: 'تکمیل' },
  ],
};

// فاز 4: حمل‌ونقل هوشمند
export const smartTransport = {
  publicTransit: {
    buses: { total: 2500, active: 2100, electric: 350, hybrid: 450 },
    metro: { lines: 7, stations: 156, dailyPassengers: 3200000 },
    taxis: { total: 65000, active: 48000, online: 35000 },
    bikes: { total: 5000, active: 3800, stations: 250 },
  },
  parking: {
    totalSpaces: 125000,
    occupied: 87500,
    available: 37500,
    smartParking: 45000,
  },
  routes: [
    { id: 1, name: 'اتوبوس خط ۱ - تجریش به راه‌آهن', passengers: 12500, onTime: 92, satisfaction: 4.5 },
    { id: 2, name: 'مترو خط ۱ - تجریش به شهرری', passengers: 450000, onTime: 96, satisfaction: 4.7 },
    { id: 3, name: 'اتوبوس برقی خط ۱۵', passengers: 8500, onTime: 94, satisfaction: 4.8 },
  ],
};

// فاز 4: مدیریت انرژی
export const energyManagement = {
  consumption: {
    total: 1250, // مگاوات
    renewable: 180, // مگاوات
    buildings: 650,
    streetLights: 120,
    trafficSystems: 80,
    waterSystems: 220,
  },
  solar: {
    totalPanels: 15000,
    totalCapacity: 45, // مگاوات
    dailyGeneration: 320, // مگاوات ساعت
    co2Saved: 125000, // تن در سال
  },
  efficiency: [
    { building: 'ساختمان شهرداری', consumption: 450, saved: 28, rating: 'A+' },
    { building: 'مرکز همایش‌ها', consumption: 380, saved: 32, rating: 'A' },
    { building: 'کتابخانه مرکزی', consumption: 220, saved: 25, rating: 'A' },
    { building: 'استادیوم آزادی', consumption: 850, saved: 18, rating: 'B+' },
  ],
  evCharging: {
    stations: 85,
    chargers: 340,
    dailyUsage: 1250,
    peakHours: ['۱۸:۰۰-۲۲:۰۰'],
  },
};
